CXX = g++

part1: Part1.cpp
	$(CXX) -o Part1 Part1.cpp 
	./Part1 input.ppm output_part1.ppm
	rm Part1
part2_1a:
	$(CXX) -o Part2_1a Part2_1a.cpp 
	./Part2_1a input.ppm output_part2_1a.ppm
	rm Part2_1a
part2_1b:
	$(CXX) -o Part2_1b Part2_1b.cpp 
	./Part2_1b input.ppm output_part2_1b.ppm
	rm Part2_1b
part2_2:
	$(CXX) -o Part2_2 Part2_2.cpp 
	./Part2_2 input.ppm output_part2_2.ppm
	rm Part2_2
part2_3:
	$(CXX) -o Part2_3 Part2_3.cpp 
	./Part2_3 input.ppm output_part2_3.ppm
	rm Part2_3